<?php
/**
 * Zend Portal
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://framework.zend.com/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   Zend
 * @copyright  Copyright (c) 2005-2007 Zend Technologies USA Inc. (http://www.zend.com)
 * @license    http://framework.zend.com/license/new-bsd     New BSD License
 * @author 
 */
echo '<?xml version="1.0" encoding="UTF-8" ?>';
$baseUrl = $this->baseUrl
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="description" content="ZPortal is your personalized Zend Protal. Add news, photos, and stuff from across the company to your portal."/>
	<link rel="icon" href="http://www.zend.com/img/favicon.ico" type="image/x-icon" />
	<link rel="shortcut icon" href="http://www.zend.com/img/favicon.ico" type="image/x-icon"/>
	<title>Zend Portal</title>	
	<link rel="stylesheet" type="text/css" href="<?php echo $baseUrl ?>/css/grids.css" />
    <script language="javascript" src="<?php echo $baseUrl ?>/js/prototype.js"></script>  
    <script language="javascript" src="<?php echo $baseUrl ?>/js/query.js"></script>
    <script language="javascript" src="<?php echo $baseUrl ?>/js/view.js?baseUrl=<?php echo $this->escape($this->url(array(), null, true)) ?>"></script>  

	<link href="<?php echo $baseUrl ?>/css/zportal.css" rel="stylesheet" type="text/css"/>	
</head>

<body>
    <div id=gbarl></div>
    <div align=right>
    <div align=right id=guser style="font-size: 84%; padding: 0 0 4px" width=100%><nobr><b><?php echo $this->user ? $this->user['email'] : "" ?></b> | 
    	<a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout'), null, true) ?>">About</a> 
    	<?php if ($this->user)  : ?> |
			<a href="<?php echo $this->url(array('controller' => 'portal', 'action' => 'view'), null, true) ?>">Personal Portal </a> |    	
    		<a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout'), null, true) ?>">Sign out</a>
    	<?php endif; ?> 
    </nobr>
    </div>
    </div>

    <div id="doc3">
    <div id="nhdrwrap">
    <div id="nhdrwrapinner">
    <div id="nhdrwrapsizer">
    <div id="gsea">
    <form id="sfrm" name="f" method="get" action="<?php echo $this->url(array('controller' => 'search', 'action' => 'index'), null, true) ?>">
    <table cellpadding="0" cellspacing="0">
    	<tr>
    		<td valign="top" class="gsealog">
    			<div id="regular_logo">&nbsp;</div>
    		</td>
    		<td align="center" class="gseain" valign="top" nowrap>
    		<br/>
    		<input type="text" name="q" id="q" size="55" maxlength="2048" value=""><br>
    		<input type="submit" value="Feed Search" name="btnG" id="btnG">
    		<input type="submit" value="Web Search" name="btnI" id="btnI"><br>
    		</td>
    		<td valign="top"><br>
    		<p class="gseaopt"></p>
    		</td>
    	</tr>
    	<tr>
    		<td align="center" colspan=3></td>
    	</tr>
    </table>
    </form>
    </div>
    </div>
    </div>
    </div>
        
    <div id="modules">
    <div class="yui-b">

	<table>
  <tr>

    <td>
	<div class="yui-gb" id="t_1">
	<?php
	if ($this->entry instanceof Exception) {
		/** @var $entry Exception */
		$entry = "";
	} else {
		$entry = $this->entry;
	}
	echo $entry;	
	?>
	</div>
	</td>
    <td valign="top">
        <?php if (!$this->user)  : ?>
    
			<div id="login" style="display:block">
			<center><h1>Sign in</h1></center>
			<center>with your Zend account</center><br/>
			<?php if($this->message) : ?> 	    
				<h3><?php echo $this->message ?></h3>
			<?php endif ?>
		
			<form method="post" name="loginForm" action="<?php echo $this->url(array('controller' => 'auth', 'action' => 'login'), null, true) ?>" >
			<table>
				<tr>
					<th>Username:</th>
					<td>
						<?php echo $this->formText('name', $this->name) ?>
					</td>
				</tr>
				<tr>
					<th>Password:</th>
					<td>
						<?php echo $this->formPassword('password', $this->password) ?>
					</td>
				</tr>		
				<tr>
					<td></td>
					<td><br/><?php echo $this->formSubmit('submit', 'Sign in') ?></td>
				</tr>
			</table>
			</form>
		</div>
    <?php endif; ?> 
  </tr>
</table>
    
    </div>
    </div>
    </div>
    
    <div id="footerwrap">
    <div id="footerwrapinner">
    <p id="footer_promos"><span class="bold_link_container">
    <a href="http://www.google.com/ig/gmchoices?hl=en">Link goes here</a>
     and more details here</span><br>
    <br>
    <span class="copyr">&copy;2007 Zend</span></p>
    </div>
    </div>
</body>
</html>