<?php
/**
 * Zend Portal
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://framework.zend.com/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   Zend
 * @copyright  Copyright (c) 2005-2007 Zend Technologies USA Inc. (http://www.zend.com)
 * @license    http://framework.zend.com/license/new-bsd     New BSD License
 * @author 
 */
echo '<?xml version="1.0" encoding="UTF-8" ?>';
$baseUrl = $this->baseUrl
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="description" content="ZPortal is your personalized Zend Protal. Add news, photos, and stuff from across the company to your portal."/>
	<link rel="icon" href="http://www.zend.com/img/favicon.ico" type="image/x-icon" />
	<link rel="shortcut icon" href="http://www.zend.com/img/favicon.ico" type="image/x-icon"/>
	<title>Zend Portal</title>	
	<link rel="stylesheet" type="text/css" href="<?php echo $baseUrl ?>/css/grids.css" />
    <script language="javascript" src="<?php echo $baseUrl ?>/js/prototype.js"></script>  
    <script language="javascript" src="<?php echo $baseUrl ?>/js/query.js"></script>
    <script language="javascript" src="<?php echo $baseUrl ?>/js/view.js?baseUrl=<?php echo $this->escape($this->url(array(), null, true)) ?>"></script>  

	<link href="<?php echo $baseUrl ?>/css/zportal.css" rel="stylesheet" type="text/css"/>	
</head>

<body>
    <div id=gbarl></div>
    <div align=right>
    <div align=right id=guser style="font-size: 84%; padding: 0 0 4px" width=100%><nobr><b><?php echo $this->user['email'] ?></b> | 
    	<a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout'), null, true) ?>">About</a> | 
    	<a href="<?php echo $this->url(array('controller' => 'portal', 'action' => 'public'), null, true) ?>">Public Portal</a> | 
    	<a href="<?php echo $this->url(array('controller' => 'portal', 'action' => 'subscribe'), null, true) ?>">My Account</a> | 
    	<a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout'), null, true) ?>">Sign out</a>
    </nobr>
    </div>
    </div>

    <div id="doc3">
    <div id="nhdrwrap">
    <div id="nhdrwrapinner">
    <div id="nhdrwrapsizer">
    <div id="gsea">
    <form id="sfrm" name="f" method="get" action="<?php echo $this->url(array('controller' => 'search', 'action' => 'index'), null, true) ?>">
    <table cellpadding="0" cellspacing="0">
    	<tr>
    		<td valign="top" class="gsealog">
    			<div id="regular_logo">&nbsp;</div>
    		</td>
    		<td align="center" class="gseain" valign="top" nowrap>
    		<br/>
    		<input type="text" name="q" id="q" size="55" maxlength="2048" value=""><br>
    		<input type="submit" value="Feed Search" name="btnG" id="btnG">
    		<input type="submit" value="Web Search" name="btnI" id="btnI"><br>
    		</td>
    		<td valign="top"><br>
    		<p class="gseaopt"></p>
    		</td>
    	</tr>
    	<tr>
    		<td align="center" colspan=3></td>
    	</tr>
    </table>
    </form>
    </div>
    </div>
    </div>
    </div>
    
    <div align=right style="padding: 0 0 0px; margin-right: 28px"> 
    	<b><a href="<?php echo $this->url(array('controller' => 'portal', 'action' => 'subscribe'), null, true) ?>">Add stuff &raquo;</a></b>
    </div>
    
    <div id="modules">
    <div class="yui-b">
    <div class="yui-gb" id="t_1">
    
    
    <script>_currentLayout='4';_layoutData = [{sizes: ['100%','0%','0%','0%'],display: ['block','none','none','none'],visibleColumns: 1},{sizes: ['48%','48%','0%','0%'],display: ['block','block','none','none'],visibleColumns: 2},{sizes: ['33%','64%','0%','0%'],display: ['block','block','none','none'],visibleColumns: 2},{sizes: ['64%','33%','0%','0%'],display: ['block','block','none','none'],visibleColumns: 2},{sizes: ['32%','32%','32%','0%'],display: ['block','block','block','none'],visibleColumns: 3},{sizes: ['21%','53%','21%','0%'],display: ['block','block','block','none'],visibleColumns: 3},{sizes: ['23%','23%','23%','23%'],display: ['block','block','block','block'],visibleColumns: 4}];</script>
    <div class="yui-u first" id="c_1" style="width: 32%; display: block;">
    
    <?php
    $feeds = $this->feeds;
    $all = sizeof($feeds);
    // prints the first column
    
    $col = floor($all / 3 + ($all % 3 > 0 ? 1 : 0)) ;
    for ($i = 0; $i < $col; $i++) {
        $feed = array_shift($feeds);
        $num = $feed[0];
        $name = $feed[1];
        ?> 

    <div id="m_<?php echo $num ?>" class="modbox">
    
        <h2 class="modtitle">
        	<a class="delbox" href="#" onclick="return itemHandler.del(<?php echo $num ?>);"></a>
        	<div id="m_<?php echo $num ?>_h">
            	<a class="mtlink" id="m_<?php echo $num ?>_url" href="source-url">
            		<span id="m_<?php echo $num ?>_link">
            			<span id="m_<?php echo $num ?>_title" class="modtitle_text"><?php echo $name ?></span>
            		</span>
            	</a>
        	</div>
        </h2>
    
        <div id="m_<?php echo $num ?>_b" class="modboxin">
        
        	<div id="FEEDmsg<?php echo $num ?>" class="statusmsg" style="display:block">
        		<span id="FEEDstatusmsg<?php echo $num ?>">Loading...</span>
    		</div>
        	<div id="FEEDdisplay<?php echo $num ?>" style="display:none">
        		<div id="FEEDentries<?php echo $num ?>"></div>
    		</div>
        
    	</div>
    </div>
        <?php
    }
    ?>
    
    <div class="dm"></div>
    </div>
    
    <div class="yui-u" id="c_2" style="width: 32%; display: block;">
    
    <?php
    $col = floor($all / 3 + ($all % 3 > 1 ? 1 : 0)) ;

    for ($i = 0; $i < $col; $i++) {
        $feed = array_shift($feeds);
        $num = $feed[0];
        $name = $feed[1];
        ?> 

    <div id="m_<?php echo $num ?>" class="modbox">
    
        <h2 class="modtitle">
        	<a class="delbox" href="#" onclick="return itemHandler.del(<?php echo $num ?>);"></a>
        	<div id="m_<?php echo $num ?>_h">
            	<a class="mtlink" id="m_<?php echo $num ?>_url" href="source-url">
            		<span id="m_<?php echo $num ?>_link">
            			<span id="m_<?php echo $num ?>_title" class="modtitle_text"><?php echo $name ?></span>
            		</span>
            	</a>
        	</div>
        </h2>
    
        <div id="m_<?php echo $num ?>_b" class="modboxin">
        
        	<div id="FEEDmsg<?php echo $num ?>" class="statusmsg" style="display:block">
        		<span id="FEEDstatusmsg<?php echo $num ?>">Loading...</span>
    		</div>
        	<div id="FEEDdisplay<?php echo $num ?>" style="display:none">
        		<div id="FEEDentries<?php echo $num ?>"></div>
    		</div>
        
    	</div>
    </div>
        <?php
    }
    ?>
    
    <div class="dm"></div>
    </div>
    
    <div class="yui-u" id="c_3" style="width: 32%; display: block;">
    <div id="lc_opt"></div>
    <?php
    $col = floor($all / 3) ;

    for ($i = 0; $i < $col; $i++) {
        $feed = array_shift($feeds);
        $num = $feed[0];
        $name = $feed[1];
        ?> 

    <div id="m_<?php echo $num ?>" class="modbox">
    
        <h2 class="modtitle">
        	<a class="delbox" href="#" onclick="return itemHandler.del(<?php echo $num ?>);"></a>
        	<div id="m_<?php echo $num ?>_h">
            	<a class="mtlink" id="m_<?php echo $num ?>_url" href="source-url">
            		<span id="m_<?php echo $num ?>_link">
            			<span id="m_<?php echo $num ?>_title" class="modtitle_text"><?php echo $name ?></span>
            		</span>
            	</a>
        	</div>
        </h2>
    
        <div id="m_<?php echo $num ?>_b" class="modboxin">
        
        	<div id="FEEDmsg<?php echo $num ?>" class="statusmsg" style="display:block">
        		<span id="FEEDstatusmsg<?php echo $num ?>">Loading...</span>
    		</div>
        	<div id="FEEDdisplay<?php echo $num ?>" style="display:none">
        		<div id="FEEDentries<?php echo $num ?>"></div>
    		</div>
        
    	</div>
    </div>
        <?php
    }
    ?>
    
    <div class="dm"></div>
    </div>
    
    <div class="yui-u" id="c_4" style="width: 0%; display: none;">
    
    <div class="dm"></div>
    </div>
    <div class="dm c">&nbsp;</div>
    </div>
    </div>
    </div>
    </div>
    
    <div id="footerwrap">
    <div id="footerwrapinner">
    <p id="footer_promos"><span class="bold_link_container">
    <a href="http://www.google.com/ig/gmchoices?hl=en">Link goes here</a>
     and more details here</span><br>
    <br>
    <span class="copyr">&copy;2007 Zend</span></p>
    </div>
    </div>
</body>
</html>
