<?php
/**
 * Zend Portal
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://framework.zend.com/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   Zend
 * @copyright  Copyright (c) 2005-2007 Zend Technologies USA Inc. (http://www.zend.com)
 * @license    http://framework.zend.com/license/new-bsd     New BSD License
 * @author 
 */

include_once 'application/models/UserRow.php';

echo '<?xml version="1.0" encoding="UTF-8" ?>';
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Register to ZendPortal</title>
</head>
<body>
	<h1>User Information</h1>
	<?php
	    if($this->message) :
      ?> 	    
	<h3><?php echo $this->message ?></h3>
	<?php endif ?>
	<form method="post">
	<table align="left">
		<tr align="left">
			<th>Email:</th>
			<td>
				<?php echo $this->formText('email', "") ?>
			</td>
		</tr>
		<tr>
			<th>Role:</th>
			<td>
				<?php echo $this->formSelect('role', "member", null, UserRow::getRoles()) ?>
			</td>
		</tr>
		<tr>
			<td></td>
			<td><?php echo $this->formSubmit('submit', 'Register') ?></td>
		</tr>
	</table>
	</form>
</body>

</html>
