<?php
/**
 * Zend Portal
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://framework.zend.com/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   Zend
 * @copyright  Copyright (c) 2005-2007 Zend Technologies USA Inc. (http://www.zend.com)
 * @license    http://framework.zend.com/license/new-bsd     New BSD License
 * @author 
 */
echo '<?xml version="1.0" encoding="UTF-8" ?>';
 ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Error</title>
</head>

<body>

<h1><?php echo $this->title ?></h1>

<?php if ($this->message): ?>
	<p>The following error occurred:</p>
	
	<?php
	$exception = $this->message;
	if ($exception->getMessage()) {
	    echo '<h3>Error</h3>';
	    echo $exception->getMessage();
	    echo '</br>';
	}
    echo '<h3>Details</h3>';
    echo str_replace("#", "<br><b>stack:</b>", $exception->getTraceAsString());
    ?>
<?php endif; ?>

</body>
</html>
